# Generated by Django 5.1.2 on 2024-11-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0001_initial'),
        ('Pessoas', '0001_initial'),
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('numero_os', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nº O.S')),
                ('data_abertura', models.DateField()),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='Pessoas.pessoas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.empresa')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'db_table': 'os',
                'ordering': ['criado', 'numero_os'],
            },
        ),
        migrations.CreateModel(
            name='ItensOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('item_numero', models.IntegerField()),
                ('peca_quantidade', models.FloatField()),
                ('peca_unitario', models.FloatField()),
                ('peca_desconto', models.FloatField()),
                ('peca_total', models.FloatField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.empresa')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peca', to='Produtos.produtos')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='Produtos.produtos')),
                ('numero_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Ordem_de_Servico.ordemservico')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'db_table': 'itensos',
                'ordering': ['criado', 'numero_os'],
                'unique_together': {('numero_os', 'item_numero')},
            },
        ),
    ]
