# Generated by Django 5.0.7 on 2024-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordem_de_Servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='numero_os',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nº O.S'),
        ),
    ]
