# Generated by Django 5.0.7 on 2024-09-03 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordem_de_Servico', '0002_alter_ordemservico_numero_os'),
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensos',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='Produtos.produtos'),
        ),
    ]
