# Generated by Django 5.0.7 on 2024-09-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='classificacao',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Fornecedor', 'Fornecedor'), ('Funcionário', 'Funcionário'), ('Vendedor', 'Vendedor'), ('Ambos', 'Ambos')], max_length=20, verbose_name='Classificação'),
        ),
    ]
