# Generated by Django 5.0.7 on 2024-09-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0003_pessoas_bairro_pessoas_cep_pessoas_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='numemro',
            field=models.IntegerField(default=0),
        ),
    ]
