# Generated by Django 5.1.2 on 2024-11-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Unidades de Medidas')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medidas',
                'db_table': 'unidadedemedida',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='precos',
            name='percentual_venda_prazo',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual sobre Preço de Venda a Prazo'),
        ),
        migrations.AlterField(
            model_name='precos',
            name='percentual_venda_vista',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual sobre Preço de Venda à Vista'),
        ),
    ]
