# Generated by Django 5.1.2 on 2024-11-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0002_unidademedida_alter_precos_percentual_venda_prazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidademedida',
            name='sigla',
            field=models.CharField(default=1, max_length=100, verbose_name='siglas'),
            preserve_default=False,
        ),
    ]
