# Generated by Django 5.1.2 on 2024-11-14 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0003_unidademedida_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='unidade_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='Produtos.unidademedida'),
        ),
    ]
