# Generated by Django 5.1.2 on 2024-11-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0004_produtos_unidade_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='ncm',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='NCM'),
        ),
    ]
