# Generated by Django 5.1.2 on 2024-11-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0006_produtos_tipo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='estoque_maximo',
            field=models.IntegerField(default=100, verbose_name='Estoque Máximo'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='estoque_minimo',
            field=models.IntegerField(default=1, verbose_name='Estoque Mínimo'),
        ),
    ]
