# Generated by Django 5.0.7 on 2024-08-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='conta_a_receber',
        ),
    ]
