# Generated by Django 5.0.7 on 2024-09-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_recebimento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Forma de Recebimento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_vendedor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do Vendedor'),
        ),
    ]
