# Generated by Django 5.0.7 on 2024-09-05 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0001_initial'),
        ('Pedidos', '0003_pedido_nome_cliente'),
        ('Pessoas', '0002_alter_pessoas_classificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='contato_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_contato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='notas_contato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='financeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Financeiro.formasrecebimento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'classificacao': 'Vendedor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='Pessoas.pessoas'),
        ),
    ]
