# Generated by Django 5.0.7 on 2024-09-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0004_pedido_contato_realizado_pedido_data_contato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Pedido'),
        ),
    ]
