# Generated by Django 5.0.7 on 2024-09-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0005_alter_pedido_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='numero_pedido',
        ),
    ]
