# Generated by Django 5.0.7 on 2024-09-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0006_remove_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'ordering': ['id'], 'verbose_name': 'Item Pedido', 'verbose_name_plural': 'Itens Pedido'},
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='criado',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='modificado',
        ),
    ]
