# Generated by Django 5.0.7 on 2024-09-12 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0007_alter_itempedido_options_remove_itempedido_ativo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'get_latest_by': 'data', 'ordering': ['criado', 'id'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
