# Generated by Django 5.0.7 on 2024-09-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0008_alter_pedido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
    ]
