# Generated by Django 5.1.2 on 2024-11-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0001_initial'),
        ('Pessoas', '0001_initial'),
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada_Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('quantidade', models.IntegerField()),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Documento')),
                ('observacoes', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.empresa')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='Pessoas.pessoas')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='Produtos.produtos')),
            ],
            options={
                'verbose_name': 'Entrada Produto',
                'verbose_name_plural': 'Entrada Produtos',
                'db_table': 'entradas',
            },
        ),
    ]
