# Generated by Django 5.1.2 on 2024-11-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaspagamento',
            name='descricao',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'Pix'), ('boleto', 'Boleto'), ('transferencia', 'Transferência Bancária')], max_length=20, verbose_name='Tipo de Recebimento'),
        ),
        migrations.AlterField(
            model_name='formasrecebimento',
            name='descricao',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'Pix'), ('boleto', 'Boleto'), ('transferencia', 'Transferência Bancária')], max_length=20, verbose_name='Tipo de Recebimento'),
        ),
    ]
