# Generated by Django 5.1.2 on 2024-11-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0002_alter_formaspagamento_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaspagamento',
            name='descricao',
            field=models.CharField(max_length=25, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='formasrecebimento',
            name='descricao',
            field=models.CharField(max_length=25, verbose_name='Tipo de Recebimento'),
        ),
    ]
