# Generated by Django 5.1.2 on 2024-11-26 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0005_licenca'),
        ('Financeiro', '0003_alter_formaspagamento_descricao_and_more'),
        ('Pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerarParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento_inicial', models.DateField()),
                ('tipo', models.CharField(choices=[('pagar', 'Pagar'), ('receber', 'Receber')], max_length=10)),
                ('documento', models.PositiveIntegerField(verbose_name='Nº do documento')),
                ('total_parcelas', models.PositiveIntegerField()),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('pagamento_total', models.BooleanField()),
                ('pagamento_parcial', models.BooleanField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.empresa')),
                ('quitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Financeiro.formasrecebimento')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerarparcela', to='Pessoas.pessoas')),
            ],
            options={
                'verbose_name': 'Gerar Parcela',
                'verbose_name_plural': 'Gerar Parcelas',
                'db_table': 'gerarparcelas',
                'ordering': ['criado', 'id'],
            },
        ),
    ]
