# Generated by Django 5.1.2 on 2024-11-21 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdemProducao', '0001_initial'),
        ('Produtos', '0006_produtos_tipo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='unidade_medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Produtos.unidademedida'),
            preserve_default=False,
        ),
    ]
