# Generated by Django 5.1.2 on 2024-11-21 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdemProducao', '0002_ordemproducao_unidade_medida'),
        ('Pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao', to='Pessoas.pessoas'),
            preserve_default=False,
        ),
    ]
