# Generated by Django 5.1.2 on 2024-11-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0003_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
